# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Deliver metadata to App Store"
  lane :metadata do
    deliver(
      skip_binary_upload: true,
      force: true
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "ReactFinlandApp.xcodeproj")
    match(type: "appstore")
    build_app(scheme: "ReactFinlandApp")
    upload_to_testflight
  end
end
